version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: fastify
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 9000:9000
